### ISSUE TITLE
Compile, Simulation 관련 문의(cov, vdb)

### ISSUE THREAD

**Issue by gju06051** [ECE4278/lab4#1]
Testbench Simulation을 하기 위해서 
.../lab4/DMAC/SIM 디렉토리를 살펴보았는데 

해당 사진과 같이 compile, simulation관련 shell파일이 각각 2개씩 존재하는데 각각 어떤 역할인지 문의 드립니다. 
![image](https://user-images.githubusercontent.com/37738888/193985272-bad1eb99-f875-4087-bb97-e69156c3ee97.png)

각각 lab4 파일을 compile 및 simulation하는데 결과는 lab4 pdf파일과 동일하게 같은 결과가 CLI에 출력 되는데 차이점이 없어서 simulation하는 환경이 다른 것인지 아니면 다른 testcase를 수행하는 것인지 아니면 무언가 제한조건이 더 붙는 것인지 궁금합니다.

**Comment by pdtowctor** [comment]
안녕하세요, Soc설계및실습 박태원입니다.

해당 내용은 lab4 github issue에 올려주시면 답변해드리도록 하겠습니다.

감사합니다,
박태원 드림

2022년 10월 5일 (수) 오후 2:10, 최보열 ***@***.***>님이 작성:

**Comment by gju06051** [comment]
저에게는 여기가 lab4 github issue로 뜨는데 혹시 오류이거나 제가 잘못 알고 있는 것이라면 알려주시면 감사하겠습니다. 

![image](https://user-images.githubusercontent.com/37738888/193986764-e9448e5e-f63c-4493-ad02-896a8726b496.png)

감사합니다. 
최보열 올림.

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.
순간 개인 메일로 보낸걸로 착각했습니다.

답변을 드리자면 우선 이번 실습에서는 run.compile, run.sim, run.verdi, run.waveform만 사용하시면 됩니다.

뒤에 4cov라고 적혀있는 script들은 이번 주 이론 수업에서 언급되는 code coverage를 확인할 때 사용하는 스크립트로, 다음 주에 자세한 설명을 들을 수 있습니다.

**Comment by gju06051** [comment]
빠른 답변 감사합니다.
