### ISSUE TITLE
lab4관련 질문

### ISSUE THREAD

**Issue by meenooksun** [ECE4278/lab4#2]
RREQ state 또는 WREQ state에서 cnt가 64보다 작을 때도 src,dst address를 64만큼 증가 혹은 감소하는 것이 맞나요 아니면 cnt 크기 만큼 증가시키는 것이 맞나요??

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

어느 쪽으로 해도 상관없습니다. cnt가 64보다 작은 경우, 어떤 값(64나 cnt값)으로 증가 시킨 후의 src/dst address는 사용하지 않기 때문입니다. (cnt가 64보다 작은 경우가 언제 발생하는 지 생각해보시면 이해할 수 있습니다.)
