### ISSUE TITLE
Wlast관련 문의

### ISSUE THREAD

**Issue by gju06051** [ECE4278/lab4#3]
wlast와 wlast_o 신호와 관련해서 이해가 안되는 점이 있습니다.

![image](https://user-images.githubusercontent.com/37738888/193992305-0278e132-4127-4761-a7c6-56fac55c3e20.png)

해당 DMAC_ENGINE에서 wlast신호 다른 신호들과 마찬가지로(ex. wvalid, arvalid...)는 always_comb에서 다루고 해당 reg type output을 출력해주기 위해서 assign 구문으로 output과 연결해주는 것으로 알고 있습니다. 그렇다면 wlast도 여타 신호들과 마찬가지로 
assign wlast_o =   wlast가 되어야 할 것 같은데 그냥 1'b1로 fix되어있는 것은 test의 편의를 위한 것인지 아니면 수정이 필요한지 궁금합니다.

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

원래는 assign wlast_o=wlast가 맞습니다. 다만 현재 확인해보니 테스트벤치 쪽에서 약간 버그가 있는 것 같아서 전부 확인 하고 다시 업데이트 상황을 공지로 알려드리도록 하겠습니다. (wlast 체크쪽에서 문제가 있는 것 같습니다.)

지금은 우선 wlast_o = 1로 뒀을 때, ppt에서 나온 simulation 결과와 일치하는지 판단해주시기 바랍니다.

**Comment by gju06051** [comment]
바쁘신 와중에 빠른 답변 감사합니다.

최보열 올림
