### ISSUE TITLE
src 주소 크기와 관련된 오류

### ISSUE THREAD

**Issue by S-JinLee** [ECE4278/lab4#7]
src 주소크기가 ffff 보다 작을 때 주소 복붙은 잘하지만 data를 읽지 못하는 것 같습니다

테스트벤치의 숫자를 바꿔가며 해보았을 때 10000 처럼 큰 주소값의 경우 잘 성공했지만
1234 등 작은 주소값일 때는 src는 랜덤, dst는 0 으로 data를 읽어오는데 이는 어떤 값과  연관되어 있는지 궁금합니다!
그래서 현재 1번 케이스만 오류가 나고 2번 케이스는 테스트를 통과하고 있습니다..

**Comment by pdtowctor** [comment]
안녕하세요, SOC설계및실습 조교 박태원입니다.

우선 제출하신 코드에서 FIFO 관련 코드(data를 FIFO에 push하고 pop하는 코드)가 없습니다. 따라서 정상적으로 동작을 못합니다.

근데 2번 케이스를 통과했다고 하셔서 이 부분이 이상하여 확인해본 결과, 테스트벤치쪽 버그가 원인이었습니다.
테스트 벤치쪽에서 AXI_SLAVE의 ADDR_WIDTH이 기본값 16으로 설정 되어있고, DMAC_TOP_TB에서는 이 기본값을 그대로 사용하여 AXI_SLAVE를 사용하기 때문에  src에서 ffff 이상일 때 버그가 발생하는 것을 확인했습니다.
검토할 때 미처 발견못한 버그인데, 이 부분 때문에 혼란을 드려 죄송합니다. 해당 버그는 정정해두겠습니다.

FIFO에 데이터를 push, pop하는 것에 대해서는 정답 코드를 올렸으니 확인해 보시길 바랍니다.

박태원 드림

**Comment by S-JinLee** [comment]
당연히 넣어야 할 한 줄을 안 넣고 엉뚱한 곳을 찾고 있었네요...
늦은 시간에 감사합니다!
